name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.126.31.21 "echo 'SSH connection successful'"

      - name: Get GitHub Runner Public IP
        id: get_runner_ip
        run: |
          echo "::set-output name=ip::$(curl -s ifconfig.me)"
      - name: Allow SSH Access Temporarily
        env:
          RUNNER_IP: ${{ steps.get_runner_ip.outputs.ip }}
        run: |
          aws ec2 authorize-security-group-ingress --group-id sg-0ad3f2e5abf1c8861 \
            --protocol tcp --port 22 --cidr ${RUNNER_IP}/32 --region ap-south-1

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.126.31.21 << EOF
          cd /home/ubuntu/node-hello || git clone  https://github.com/johnpapa/node-hello.git /home/ubuntu/node-hello && cd /home/ubuntu/node-hello
          git pull origin main
          npm install
          pm2 restart all || pm2 start app.js
          EOF
