name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Get GitHub Runner Public IP
        id: get_runner_ip
        run: |
          echo "::set-output name=ip::$(curl -s ifconfig.me)"
      - name: Allow SSH Access Temporarily
        env:
          RUNNER_IP: ${{ steps.get_runner_ip.outputs.ip }}
        run: |
          aws ec2 authorize-security-group-ingress --group-id sg-xxx \
            --protocol tcp --port 22 --cidr ${RUNNER_IP}/32 --region us-east-1

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> << EOF
          cd /home/ec2-user/node-hello || git clone https://github.com/username/node-hello.git /home/ec2-user/node-hello && cd /home/ec2-user/node-hello
          git pull origin main
          npm install
          pm2 restart all || pm2 start app.js
          EOF
